### ISSUE TITLE
How to use the API

### ISSUE THREAD

**Issue by kargarisaac** [paperswithcode/axcell#16]
Hi,

I'm trying to run the notebooks and use your pre-trained model to test it on a paper. I use the `extraction.ipynb` and `results-extraction.ipynb` notebooks but get some errors. It seems it needs to download data. For example in the `extraction.ipynb` notebook I get this:

![image](https://user-images.githubusercontent.com/24753756/96629940-f2e46b00-131c-11eb-83e2-0dc04663d4bd.png)

What folders and directories should be created and what data should I download? It's not clear for me.

I also downloaded three dataset csv and json files and put them in the scripts folder and run `download_arxiv_s3_papers.sh`, but I get an error again:

```
fatal error: Unable to locate credentials
warning: failed to load external entity "arXiv_src_manifest.xml"
```
I cannot find the `arXiv_src_manifest.xml` file.

Thanks

**Comment by mkardas** [comment]
Hi,

please see [this comment regarding testing the pipeline on a single file](https://github.com/paperswithcode/axcell/issues/9#issuecomment-648345880) and [this comment regarding downloading of the papers](https://github.com/paperswithcode/axcell/issues/13#issuecomment-665811726). Please note that `download_arxiv_s3_papers.sh` uses `requester-pays` [arXiv's bulk data access s3 bucket](https://arxiv.org/help/bulk_data_s3), so you need to configure valid AWS credentials (the configured account will be charged for the bandwidth used). Unfortunately due to licensing of arXiv papers we cannot provide the dataset.
