### ISSUE TITLE
file not found in AWS S3

### ISSUE THREAD

**Issue by purnasrivatsa96** [paperswithcode/axcell#23]
I have configured my AWS CLI and i'm able to download arxiv_src_manifest.xml file and the code creates tars.txt but fails as shown below -- 

![Capture](https://user-images.githubusercontent.com/25502390/141050657-7f3cb738-ae08-4af0-90e4-0edcad389dc7.PNG)

How do i resolve this?

**Comment by mkardas** [comment]
Hi,

from the first line it seems the script is run on Windows (`.\arXiv_src_manifest.xml` instead of `./arXiv_src_manifest.xml`), which might cause issues due to the way paths are encoded. The script uses simple pattern matching to select files to download, so you may have to change backslashes to slashes or update the script. You can also just download couple of papers manually to test rest of the pipeline, though it won't be easy to make it work on Windows, as pointed in https://github.com/paperswithcode/axcell/issues/22#issuecomment-963001517.

Also, keep in mind that arXiv S3 bucket is a requester pays bucket (https://arxiv.org/help/bulk_data_s3).

**Comment by purnasrivatsa96** [comment]
Got it. thanks!
