### ISSUE TITLE
Metric for Table Segmentation

### ISSUE THREAD

**Issue by YuzeLou** [paperswithcode/axcell#25]
It looks like the following code in `nbsvm.py` is used to compute precision and recall for the cell type classification task:
```
def metrics(preds, true_y):
    
    y = true_y
    p = preds
    acc = (p == y).mean()
    tp = ((y != 0) & (p == y)).sum()
    fp = ((p != 0) & (p != y)).sum()
    fn = ((y != 0) & (p == 0)).sum()
    prec = tp / (fp + tp)
    reca = tp / (fn + tp)
    return {
        "precision": prec,
        "accuracy": acc,
        "recall": reca,
        "TP": tp,
        "FP": fp,
    }
```
My understanding is that you are trying to exclude OTHER. Then why `fp` is not calculated as ` fp = ((y != 0) & (p != y)).sum()`? Also, why not use the standard way that treats all classes identically?

**Comment by mkardas** [comment]
Hi Yuze,

with the current implementation, the precisions `prec` means: if a model classifies a cell as a particular non-OTHER class C, what is the chance that it's C in fact.

You can see that with this definition, the denominator of `prec` depends only on `p` as expected:

```
tp = [(y != 0) & (p == y)] = [(p != 0) & (p == y)]
tp + fp = [(p != 0) & (p == y)] + [(p != 0) & (p != y)] = [(p != 0) & (p == y | p != y)] = (p != 0)
```

With your suggestion we would get `tp + fp' = (y != 0)` which doesn't depend on predictions at all.

We don't treat all classes identically, because non-OTHER classes have much higher impact on the later stages of the pipeline.

**Comment by YuzeLou** [comment]
Thanks for the response. That explanation for `prec` makes sense.

But how do you interpret recall `reca`? `tp + fn = [(y != 0) & (p == y) + (y != 0) & (p == 0)] != (y != 0)`

**Comment by mkardas** [comment]
`reca` is between a recall with multiple positive classes (`[(y != 0) & (p == y)] / (y != 0)`) and a binary recall (`[(y != 0) & (p != 0)] / (y != 0)`). Using one of these two would work as well.
