### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by ymohit** [paperswithcode/axcell#8]
Thanks for sharing your code. I have a quick question for you guys:

It seems to me that the file ("pwc/papers-with-abstracts.json") required to execute  axcell/scripts/download_arxiv_s3_papers.sh is missing.  How can I fetch this file? 

Does this step (https://github.com/ymohit/axcell/blob/master/scripts/download_arxiv_s3_papers.sh#L10) list arxiv papers mentioned in csvhttps://github.com/paperswithcode/axcell/releases/download/v1.0/arxiv-papers.csv.xz or its a different list?

Thanks

**Comment by mkardas** [comment]
Hi,
`papers-with-abstracts.json` can be downloaded from [here](https://github.com/paperswithcode/paperswithcode-data). You can also create `wildcards.txt` directly from `arxiv-papers.csv.xz` with the following:
```python
import pandas as pd, re
arxiv_no_version = re.compile(r'^(\d+\.\d+)(v\d+)?$')
ids = pd.read_csv('arxiv-papers.csv.xz')['arxiv_id']
ids = ids.str.replace(arxiv_no_version, r'/\1.')
ids.to_csv('wildcards.txt', header=False, index=False)
```
Keep in mind that papers backed up on arXiv's S3 bucket are not versioned (that's why we publish hashes of each e-print) and are mostly v1.
