### ISSUE TITLE
Inquiry about file path in notebooks

### ISSUE THREAD

**Issue by TC1997** [paperswithcode/axcell#9]
Hello! I am working on reproducing the results in Jupyter notebooks on macOS but I have some questions on the following code in terms of the file path:
 **ROOT_PATH = Path('data')**
**PWC_LEADERBOARDS_ROOT_PATH = Path('pwc-laderboards')**
How to deal with the file path on macOS? I cannot find the mentioned directory **'data'** under **/axcell-master/notebooks**, where can I download the required file? Whether should I create the directory named **data** under **/axcell-master/notebooks**?
Looking forward to your kind reply

**Comment by mkardas** [comment]
Hi,
the directory pointed by `ROOT_PATH` is a working directory where consecutive pipeline steps take inputs from and save outputs to. `ROOT_PATH` can be any directory and a `ROOT_PATH / "sources"` subdirectory should contain archived e-prints of papers to process. You can see in [this notebook](notebooks/extraction.ipynb) how the directory should look like before extraction (with a single e-print archive for paper 1903.11816v1, as downloaded from http://export.arxiv.org/e-print/1903.11816v1) and how it looks like after the extraction. Try to test that notebook on a single e-print to make sure everything is set up correctly. Then you can put more articles and rerun the extraction. Due to license of articles we cannot provide them.

The difference between `ROOT_PATH` and `PWC_LEADERBOARDS_ROOT_PATH` is that the later should contain only the sources of articles present in the PWC Leaderboards dataset.

Thanks for taking the time and effort to reproduce our work! Do not hesitate to ask if you have more questions.
